services:
  sirius-prism:
    image: stoplight/prism:4.14.1
    container_name: lpa-sirius-prism
    command:
      - mock
      - --cors
      - -h
      - 0.0.0.0
      - -p
      - "4010"
      - /tmp/sirius.yml
    volumes:
      - ./sirius.yml:/tmp/sirius.yml:ro

  sirius-gateway:
    image: nginx:1.27.3-alpine
    container_name: lpa-sirius-gateway
    depends_on:
      - sirius-prism
    volumes:
      - ./mock-sirius.nginx:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "7010:80"
